version: "3"

services:
  mongodb: 
    container_name: mongodb
    image: mongo
    ports:
      - "5003:27017"
  cls-oee-ssr:
    container_name: cls-oee-ssr
    image: ivensleos/cls-oee-ssr
    restart: always
    build: .
    environment:
      - VITE_STRAPI_URL=http://127.0.0.1:1337/
      - VITE_MONGODB_URI=mongodb://mongodb:27017/
      - VITE_MONGODB_DB=CLS_OEE
      - DATABASE_HOST=mongodb
      - DATABASE_PORT=27017
      - DATABASE_NAME=CLS_OEE
    ports:
      - "5000:3000"
      - "5001:1337"
    links:
      - mongodb